# Generated by Django 3.0.3 on 2020-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='link',
            field=models.CharField(max_length=2048),
        ),
    ]
