# Generated by Django 3.0.3 on 2020-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reals', '0002_auto_20200603_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='bath',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='search',
            name='beds',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='search',
            name='price',
            field=models.CharField(max_length=225),
        ),
    ]
