# Generated by Django 3.0.3 on 2020-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reals', '0003_auto_20200603_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.AlterField(
            model_name='search',
            name='bath',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='search',
            name='beds',
            field=models.CharField(max_length=3),
        ),
    ]
