# Generated by Django 3.0.3 on 2020-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reals', '0005_search_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='priority',
            field=models.BooleanField(default=True),
        ),
    ]
