# Generated by Django 3.0.7 on 2020-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reals', '0006_auto_20200609_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
